"""Generate worker/seed.sql — the questions and answer key, ready for D1.

    py -3 make_seed.py
    cd worker
    wrangler d1 execute estimathon --remote --file=./seed.sql

Reads the same sources as everything else: question text and order from
estimathon.js (or questions.json if you moved them there), answers from
answers.json. The generated file contains the answer key, so it is gitignored
alongside answers.json — regenerate it whenever you change either source.

Re-running is safe: it upserts by question id and leaves each question's
pending/open/closed status alone, so you can fix a typo mid-event without
resetting the run of play.
"""

import sys
from pathlib import Path

from questions import load_questions

HERE = Path(__file__).resolve().parent
OUT = HERE / "worker" / "seed.sql"


def sql_string(value):
    return "'" + str(value).replace("'", "''") + "'"


def sql_number(value):
    return "NULL" if value is None else repr(float(value))


def build(questions):
    lines = [
        "-- Generated by make_seed.py. Do not edit; do not commit.",
        "-- Contains the answer key.",
        "",
    ]
    for i, q in enumerate(questions):
        lines.append(
            "INSERT INTO questions (id, position, text, unit, answer) VALUES "
            "(%s, %d, %s, %s, %s)\n"
            "  ON CONFLICT(id) DO UPDATE SET position = excluded.position, "
            "text = excluded.text, unit = excluded.unit, answer = excluded.answer;"
            % (sql_string(q["id"]), i, sql_string(q["text"]),
               sql_string(q["unit"]), sql_number(q["answer"]))
        )

    # Anything left in D1 that is no longer a question should go.
    keep = ", ".join(sql_string(q["id"]) for q in questions)
    lines.append("")
    lines.append("DELETE FROM questions WHERE id NOT IN (%s);" % keep)
    lines.append("")
    return "\n".join(lines)


def main():
    questions = load_questions()
    keyed = sum(1 for q in questions if q["answer"] is not None)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(questions), encoding="utf-8")

    print("wrote %s" % OUT)
    print("  %d questions, %d with an answer" % (len(questions), keyed))
    if keyed < len(questions):
        missing = [q["id"] for q in questions if q["answer"] is None]
        print("  no answer yet for: %s" % ", ".join(missing))
        print("  (fine -- type them into the dashboard, or fill in answers.json)")
    print("\nNext:")
    print("  cd worker")
    print("  wrangler d1 execute estimathon --remote --file=./seed.sql")
    return 0


if __name__ == "__main__":
    sys.exit(main())
